### ISSUE TITLE
Home page looks blank

### ISSUE THREAD

**Issue by AbhyudayaSharma** [jenkinsci/jfr-action-doc#3]
### Describe your use-case which is not covered by existing documentation.

The home page for the documentation looks empty. I would suggest adding at least some description.

![image](https://user-images.githubusercontent.com/11471599/189000873-c02d7d8b-6039-4706-b548-e810467f1cb4.png)

@krisstern @Cr1t-GYM

**Comment by krisstern** [comment]
Yeah, we could definitely add a brief description there stating our purposes, for example.
